const labels: Record<string, string> = {
  '01': 'Assessment and psychopathology',
  '02': 'Risk, emergencies, ethics and Greek law',
  '03': 'Psychosis and schizophrenia',
  '04': 'Depression and bipolar disorders',
  '05': 'Anxiety, OCD, trauma, dissociation and somatic presentations',
  '06': 'Personality disorders',
  '07': 'Substance use and behavioural addictions',
  '07b': 'Impulse-control disorders',
  '08': 'Neurocognitive and older-adult psychiatry',
  '09': 'Liaison and psychosomatic psychiatry',
  '10': 'Neurodevelopmental and child psychiatry',
  '11': 'Eating, sleep, sexual and reproductive psychiatry',
  '12': 'Pharmacology and antipsychotics',
  '13': 'Clozapine, antidepressants and mood stabilisers',
  '14': 'Other medicines and special populations',
  '15': 'Biological therapies and psychotherapy',
  '16': 'Neuroscience, genetics and methodology',
  '17': 'Forensic and community psychiatry',
}
const greek: Record<string, string> = {
  '01': 'Αξιολόγηση και ψυχοπαθολογία',
  '02': 'Κίνδυνος, επείγοντα, δεοντολογία και ελληνικό δίκαιο',
  '03': 'Ψυχώσεις και σχιζοφρένεια',
  '04': 'Κατάθλιψη και διπολικές διαταραχές',
  '05': 'Άγχος, ΙΨΔ, τραύμα, διάσχιση και σωματικά συμπτώματα',
  '06': 'Διαταραχές προσωπικότητας',
  '07': 'Χρήση ουσιών και συμπεριφορικές εξαρτήσεις',
  '07b': 'Διαταραχές ελέγχου παρορμήσεων',
  '08': 'Νευρογνωστικές διαταραχές και ψυχιατρική ηλικιωμένων',
  '09': 'Διασυνδετική και ψυχοσωματική ψυχιατρική',
  '10': 'Νευροαναπτυξιακές διαταραχές και παιδοψυχιατρική',
  '11': 'Διατροφικές διαταραχές, ύπνος, σεξουαλική και αναπαραγωγική ψυχιατρική',
  '12': 'Φαρμακολογία και αντιψυχωσικά',
  '13': 'Κλοζαπίνη, αντικαταθλιπτικά και σταθεροποιητές διάθεσης',
  '14': 'Άλλα φάρμακα και ειδικοί πληθυσμοί',
  '15': 'Βιολογικές θεραπείες και ψυχοθεραπεία',
  '16': 'Νευροεπιστήμες, γενετική και μεθοδολογία',
  '17': 'Ψυχιατροδικαστική και κοινοτική ψυχιατρική',
}
export const domainName = (id: string, locale: 'en' | 'el' = 'en') =>
  (locale === 'el' ? greek : labels)[id] ?? (locale === 'el' ? 'Ενότητα ' : 'Domain ') + id
